---
title: "Holy, Holy, Holy"
categories: ["Worship", "Praise"]
song_id: "S002"
song_language: "English"
song_type: "Hymn"
key: "D"
composer: "Reginald Heber"
folder: "Folder 1"
audio: ""
has_audio: ""
---

::: {.song-info}
Language: {{< meta song_language >}}  |  Type: {{< meta song_type >}}  |  Key: {{< meta key >}}  |  Composer: {{< meta composer >}}  |  Vestry folder: {{< meta folder >}}
:::

::: {.lyrics}
### Verse 1
| Holy, holy, holy! Lord God Almighty!
| Early in the morning our song shall rise to Thee;
| Holy, holy, holy, merciful and mighty!
| God in three Persons, blessed Trinity!

### Verse 2
| Holy, holy, holy! Angels adore Thee,
| Casting down their golden crowns around the glassy sea;
| Thousands and ten thousands worship low before Thee,
| Which wert, and art, and evermore shalt be.

### Verse 3
| Holy, holy, holy! though the darkness hide Thee,
| Though the eye of sinful man Thy glory may not see;
| Only Thou art holy; there is none beside Thee,
| Perfect in power, in love, and purity.

### Verse 4
| Holy, holy, holy! Lord God Almighty!
| All Thy works shall praise Thy name, in earth, and sky, and sea;
| Holy, holy, holy; merciful and mighty!
| God in three Persons, blessed Trinity!
:::

