---
title: "Oba ni Jesu"
categories: ["Worship", "Praise"]
song_id: "S006"
song_language: "Yoruba"
song_type: "Special Number"
key: "F"
composer: "Unknown"
folder: "Folder 1"
audio: ""
has_audio: ""
---

::: {.song-info}
Language: {{< meta song_language >}}  |  Type: {{< meta song_type >}}  |  Key: {{< meta key >}}  |  Composer: {{< meta composer >}}  |  Vestry folder: {{< meta folder >}}
:::

::: {.lyrics}
### Chorus
| Oba ni o, oba ni Jesu o
| Oba ni o, oba ni se
| Oun fun ni layo, oun munu eni dun
| Oba ni Jesu, egbeega. /2ce

### Duet 1
| Oun fun ni layo, oun dani lare
| Oun gbeniga oun gbeni nija
| Wa kalo juba, Olorun iyanu
| Oba ni Jesu, egbeega

### Duet 2
| Oun dani lare, oun segun fun ni
| Oun gbani sile lowo aiye o
| Ewa wo Jesu oonise iyanu
| Oba ni Jesu egbeega

### Chorus
| Oba ni o, oba ni Jesu o
| Oba ni o, oba ni se
| Oun fun ni layo, oun munu eni dun
| Oba ni Jesu, egbeega. /2ce

### Duet 3
| Ato bani se ni, ato gbara le ni
| Ato farati ni, ohun lalabora
| Ewa wo Jesu, aadani magbagbe
| Oba ni Jesu, egbeega.

### Chorus
| Oba ni o, oba ni Jesu o
| Oba ni o, oba ni se
| Oun fun ni layo, oun munu eni dun
| Oba ni Jesu, egbeega. /2ce

### Duet 4
| Egbeega o, egbeega o
| Egbeega o olagbara pupo
| Oruko Jesu, oun dani nide
| Oba ni Jesu egbeega

### Chorus
| Oba ni o, oba ni Jesu o
| Oba ni o, oba ni se
| Oun fun ni layo, oun munu eni dun
| Oba ni Jesu, egbeega. /2ce

### Vocal 1
| Oba ni

### Chorus
| Oba ni o, oba ni Jesu o
| Oba ni o, oba ni se
| Oun fun ni layo, oun munu eni dun
| Oba ni Jesu, egbeega. /2ce

### Vocal 2
| Oba ni

### Chorus
| Oba ni o, oba ni Jesu o
| Oba ni o, oba ni se
| Oun fun ni layo, oun munu eni dun
| Oba ni Jesu, egbeega. /2ce
:::

